use std::env;
use std::fs;
use std::path::Path;

struct RouteInfo {
    mod_name: String,
    route_path: String,
    abs_path: String,
}

fn collect_routes(dir: &Path, base_dir: &Path, routes: &mut Vec<RouteInfo>) {
    if !dir.exists() {
        return;
    }

    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_routes(&path, base_dir, routes);
            } else if path.is_file() {
                if let Some(ext) = path.extension() {
                    if ext == "rs" {
                        let file_stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
                        if file_stem != "mod" && !file_stem.starts_with('_') && !file_stem.starts_with('.') {
                            if let Ok(rel) = path.strip_prefix(base_dir) {
                                let rel_str = rel.to_string_lossy().replace('\\', "/");
                                let route_path = format!("/{}", rel_str);
                                let mod_name = format!(
                                    "route_{}",
                                    rel_str
                                        .replace('/', "_")
                                        .replace('.', "_")
                                        .replace('-', "_")
                                );
                                let abs_path = path
                                    .canonicalize()
                                    .unwrap_or_else(|_| path.clone())
                                    .to_string_lossy()
                                    .to_string();

                                routes.push(RouteInfo {
                                    mod_name,
                                    route_path,
                                    abs_path,
                                });
                            }
                        }
                    }
                }
            }
        }
    }
}

fn main() {
    println!("cargo:rerun-if-changed=src/routes");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("dynamic_routes.rs");

    let routes_dir = Path::new("src/routes");
    let mut routes = Vec::new();
    collect_routes(routes_dir, routes_dir, &mut routes);
    routes.sort_by(|a, b| a.route_path.cmp(&b.route_path));

    let mut generated_code = String::new();
    generated_code.push_str("// Auto-generated by build.rs - DO NOT EDIT MANUALLY\n\n");

    for r in &routes {
        generated_code.push_str(&format!(
            "#[path = \"{}\"]\npub mod {};\n",
            r.abs_path, r.mod_name
        ));
    }

    generated_code.push_str("#[allow(unused_mut)]\n");
    generated_code.push_str("pub fn build_dynamic_router() -> axum::Router {\n");
    generated_code.push_str("    let mut r = axum::Router::new();\n");
    for r in &routes {
        // https://domain/path/to/file.rs -> ./src/routes/path/to/file.rs
        generated_code.push_str(&format!(
            "    r = r.nest(\"{}\", {}::router());\n",
            r.route_path, r.mod_name
        ));
    }
    generated_code.push_str("    r\n");
    generated_code.push_str("}\n\n");

    generated_code.push_str("#[allow(dead_code)]\n");
    generated_code.push_str("pub fn get_available_routes() -> &'static [&'static str] {\n");
    generated_code.push_str("    &[\n");
    for r in &routes {
        generated_code.push_str(&format!("        \"{}\",\n", r.route_path));
    }
    generated_code.push_str("    ]\n");
    generated_code.push_str("}\n");

    fs::write(dest_path, generated_code).unwrap();
}
